// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BaseIdentification interface {
	IsBaseIdentification()
	GetUUID() *string
	GetLabel() *string
}

type MemberLoginResponse interface {
	IsMemberLoginResponse()
}

type Error struct {
	Message     string  `json:"message"`
	Description *string `json:"description,omitempty"`
}

func (Error) IsMemberLoginResponse() {}

type Institution struct {
	UUID  *string `json:"uuid,omitempty"`
	Label *string `json:"label,omitempty"`
	Name  *string `json:"name,omitempty"`
}

func (Institution) IsBaseIdentification()  {}
func (this Institution) GetUUID() *string  { return this.UUID }
func (this Institution) GetLabel() *string { return this.Label }

type LoginCredentials struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Medication struct {
	UUID  *string `json:"uuid,omitempty"`
	Label *string `json:"label,omitempty"`
	Name  *string `json:"name,omitempty"`
}

func (Medication) IsBaseIdentification()  {}
func (this Medication) GetUUID() *string  { return this.UUID }
func (this Medication) GetLabel() *string { return this.Label }

type MedicationToTake struct {
	IntOfTime   *int        `json:"intOfTime,omitempty"`
	IsAvailable *bool       `json:"isAvailable,omitempty"`
	QuantityPer *int        `json:"quantityPer,omitempty"`
	TimeMeasure *string     `json:"timeMeasure,omitempty"`
	Medication  *Medication `json:"medication,omitempty"`
}

type Member struct {
	UUID     *string     `json:"uuid,omitempty"`
	Label    *string     `json:"label,omitempty"`
	Name     *string     `json:"name,omitempty"`
	Password *string     `json:"password,omitempty"`
	Token    *string     `json:"token,omitempty"`
	Username *string     `json:"username,omitempty"`
	Email    *string     `json:"email,omitempty"`
	MemberOf []*MemberOf `json:"MemberOf,omitempty"`
}

func (Member) IsBaseIdentification()  {}
func (this Member) GetUUID() *string  { return this.UUID }
func (this Member) GetLabel() *string { return this.Label }

func (Member) IsMemberLoginResponse() {}

type MemberOf struct {
	Role        *string      `json:"role,omitempty"`
	Institution *Institution `json:"institution,omitempty"`
}

type Pacient struct {
	UUID  *string `json:"uuid,omitempty"`
	Label *string `json:"label,omitempty"`
	Name  *string `json:"name,omitempty"`
}

func (Pacient) IsBaseIdentification()  {}
func (this Pacient) GetUUID() *string  { return this.UUID }
func (this Pacient) GetLabel() *string { return this.Label }
