// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type BaseIdentification interface {
	IsBaseIdentification()
	GetUUID() *string
	GetLabel() *string
}

type Institution struct {
	UUID  *string `json:"uuid"`
	Label *string `json:"label"`
	Name  *string `json:"name"`
}

func (Institution) IsBaseIdentification()  {}
func (this Institution) GetUUID() *string  { return this.UUID }
func (this Institution) GetLabel() *string { return this.Label }

type LoginCredentials struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type Medication struct {
	UUID  *string `json:"uuid"`
	Label *string `json:"label"`
	Name  *string `json:"name"`
}

func (Medication) IsBaseIdentification()  {}
func (this Medication) GetUUID() *string  { return this.UUID }
func (this Medication) GetLabel() *string { return this.Label }

type MedicationToTake struct {
	IntOfTime   *int        `json:"intOfTime"`
	IsAvailable *bool       `json:"isAvailable"`
	QuantityPer *int        `json:"quantityPer"`
	TimeMeasure *string     `json:"timeMeasure"`
	Medication  *Medication `json:"medication"`
}

type Member struct {
	UUID     *string     `json:"uuid"`
	Label    *string     `json:"label"`
	Name     *string     `json:"name"`
	Password *string     `json:"password"`
	Token    *string     `json:"token"`
	MemberOf []*MemberOf `json:"MemberOf"`
}

func (Member) IsBaseIdentification()  {}
func (this Member) GetUUID() *string  { return this.UUID }
func (this Member) GetLabel() *string { return this.Label }

type MemberOf struct {
	Role        *string      `json:"role"`
	Institution *Institution `json:"institution"`
}

type Pacient struct {
	UUID  *string `json:"uuid"`
	Label *string `json:"label"`
	Name  *string `json:"name"`
}

func (Pacient) IsBaseIdentification()  {}
func (this Pacient) GetUUID() *string  { return this.UUID }
func (this Pacient) GetLabel() *string { return this.Label }
